[project]
name = "cython-scribbles"
version = "0.0.1"
requires-python = '>=3.14'

[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools >= 77.0.3",
  "Cython>=3.2.4,<4",
]

[project.optional-dependencies]
build-dev = [
  "setuptools >= 77.0.3",
  "Cython>=3.2.4,<4",
  "cython-lint",
]
dev = [
  "pytest",
  "ruff",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
src = ["src"]
line-length = 100
