name: build and test

on:
  push:
    branches: main
    paths-ignore:
      - '.gitignore'
      - '*.md'

jobs:
  build-and-test:
    strategy:
      matrix:
        platform:
          - ubuntu-24.04
          - macos-15

    name: "runs-on=${{ matrix.platform }}"
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: 3.14
      - run: python -c "import sys; print(sys.version)"
      - run: make install_build_tools
      - run: make build_debug
      - run: make clean
      - run: make dev_install
      - run: make test
