name: build and test

on:
  push:
    branches: main
    paths-ignore:
      - '.gitignore'
      - '*.md'

jobs:
  build-and-test:
    strategy:
      matrix:
        platform:
          - ubuntu-24.04
          - macos-15

    name: "runs-on=${{ matrix.platform }}"
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - run: python -c "import sys; print(sys.version)"
      - run: python -c "from tomllib import load; print('\n'.join(load(open('pyproject.toml', 'rb'))['build-system']['requires']))" > build-requires.txt
      - run: pip install -r build-requires.txt
      - run: make build_debug
      - run: make clean
      - run: make dev_install
      - run: make test
